### PR TITLE
PMD bugs fixing in volunteer-android

### LINKED ISSUE #121: PMD bugs in volunteer-android
## Description
As a Developer
I need to fix the following PMD bugs,
so that the code is clean.

### Update [Required]
- [ ] The field name indicates a constant but its modifiers do not (MainActivity.java Line 42)
- [ ] The field name indicates a constant but its modifiers do not (MainActivity.java Line 46)
- [ ] Use equals() to compare strings instead of '==' or '!=' (MainActivity.java Line 72)
- [ ] Use equals() to compare strings instead of '==' or '!=' (MainActivity.java Line 85)
- [ ] Use equals() to compare strings instead of '==' or '!=' (MainActivity.java Line 163)
- [ ] These nested if statements could be combined (MainActivity.java Line 269)
- [ ] Avoid using if...else statements without curly braces (MainActivity.java Line 305)
- [ ] Use equals() to compare strings instead of '==' or '!=' (EventListAdapter.java Line 68)
- [ ] Avoid printStackTrace(); use a logger call instead. (HttpHandler.java Line 53)
- [ ] Avoid printStackTrace(); use a logger call instead. (HttpHandler.java Line 58)
- [ ] A getX() method which returns a boolean should be named isX() (PreferenceManager.java Line 35)

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

### PR DESCRIPTION
**Pull request by sviho**
Fixes #121 

### Type of Change:
- Code
- Quality Assurance

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

### Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by sviho** [comment]
@roopalJazz maybe I'm wrong, but there's no MainActivity.java file in the repository. I thought file MenuActivity.java was meant instead, wasn't it?

**Comment by sviho** [comment]
Also, there's no PreferenceManager.java, only PrefManager.java. I couldn't find the part getX() in it, there's no such a line

**Comment by aayushinigam** [comment]
@sviho I think you checked out a different branch. You'll find these classes in gsoc18-infra branch.

**Comment by roopalJazz** [comment]
@sviho @aayushinigam is right. The latest code is in gsoc18-infra branch.

**Comment by aayushinigam** [comment]
@sviho Are you working on this?

**Comment by sviho** [comment]
@aayushinigam No

**Pull request closed without merging**
