### PR TITLE
Added Schema, screenshots , workflow

### PR DESCRIPTION
**Pull request by pandilladivya**

### CODE REVIEW

**Comment by HimanshiJain** [comment]
1. Schema - should we explain some fields like needsVolunteers and the ones not too obvious? And how would it affect the app flow?

2. Mock ups are fine except the event registration activity. We discussed right what fields we needed the user to input and what we are taking from their account details?

3. Nice workflow flowcharts! good work :D. Although in the Events page of that PDF shouldn't we mention explicitly that for registering, the user needs to login first and can't register anonymously?

So this brings me to another discussion, should we allow bookmarking the events even if they are not registered? what do you think @sandarumk ?

**Comment by sandarumk** [comment]
For now, let's keep it aside and add as an issue which can be finished if we have time.

**Comment by HimanshiJain** [comment]
Cool, I will create the issue for this.

**Comment by pandilladivya** [comment]
@HimanshiJain @sandarumk 
Done with the changes. Kindly review

**Comment by pandilladivya** [comment]
@HimanshiJain Okay sure :)

**Pull request merged**
