### PR TITLE
Application Flow.

### PR DESCRIPTION
**Pull request by pandilladivya**
**Tasks done in this PR**

1. Whenever a user installs the application for the first time, show the user the login page as the initial screen until the user logs in.

2. Once the user login/signup the default page should be homepage.

I've written a separate class to handle this behaviour.
@sandarumk @HimanshiJain Kindly review.
Thank you 😊 ☺️

### CODE REVIEW

**Comment by sandarumk** [comment]
Again the base branch is wrong.

**Comment by pandilladivya** [comment]
Sorry, Will update

**Comment by sandarumk** [comment]
@pandilladivya Check all the other places too

**Comment by pandilladivya** [comment]
Closing this PR due to Etouches conflicts

**Pull request closed without merging**
