### PR TITLE
Application Login Flow.

### PR DESCRIPTION
**Pull request by pandilladivya**
Once the user logs in to the application, Login page is not shown to the user again until they logout or uninstalls the application.

If the user skips sign in, user is redirected to the homepage and login page is shown again when the user reopens the app / reruns the app. ( this will be changed in future at the time of event registrations )

@HimanshiJain @sandarumk 
Kindly review this PR, It is independent of Etouches.

### CODE REVIEW

**Comment by sandarumk** [comment]
Is this dependent on any other PRs which are already on the list? I see commits for migrating the systers firebase and change project colors here. These were the two PRs we discussed with last night  meeting right?

**Comment by pandilladivya** [comment]
@sandarumk Yes.
Its dependent on #63 
Will modify this once #63 gets merged :)

**Comment by sandarumk** [comment]
Sure in future PRs, if as a good practice, mention in the PR if it is dependent on any other.

**Comment by pandilladivya** [comment]
Closing this PR.
Ref #68

**Pull request closed without merging**
