### PR TITLE
Navigate to the event

### PR DESCRIPTION
**Pull request by pandilladivya**
Navigate to the event when user clicks on the navigate icon in the schedule page.

### CODE REVIEW

**Comment by sandarumk** [comment]
Keep in mind the commit message changes that I told you many times.

**Comment by HimanshiJain** [comment]
@pandilladivya Can you add a mock event in India or nearby in the Firebase Database to check this functionality, because it shows no route for the currently added events.

**Comment by pandilladivya** [comment]
Yeah. I have added two in India.

**Comment by sandarumk** [comment]
resolve the conflicts too.

**Comment by pandilladivya** [comment]
@sandarumk Rebased this branch onto 1.2 and resolved conflicts.

**Comment by sandarumk** [comment]
@HimanshiJain Do you have any concerns about this? If not proceed with the merge.

**Comment by sandarumk** [comment]
Since @HimanshiJain seems to have no concerns I am merging.

**Pull request merged**
